apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex
  annotations:
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ .Values.certManagerClusterIssuer }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingressHost }}
      secretName: {{ .Values.ingressHost }}-tls
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dex
            port:
              number: 5556
