calico:
  networkMTU: 1500
  image: calico/node:v3.16.4
  cniImage: calico/cni:v3.16.4
  controllersImage: calico/kube-controllers:v3.16.4
  flexvolDriverImage: calico/pod2daemon-flexvol:v3.16.4
  enableReporting: false
  networkIpAutodetectionMethod: first-found
  ipipEnabled: true
  vxlanEnabled: false
  # Add something like `- --bird-ready` with correct indentation
  ipipReadiness: ""
  podCIDR: 10.2.0.0/16
  networkEncapsulation: "ipipMode: Always"
  blockedMetadataCIDRs: []
  # Lokomotive specific change.
  # failsafeInboundHostPorts:
  encryptPodTraffic: false
