monitoring:
  enable: false

contour:
  image: docker.io/projectcontour/contour
  tag: v1.13.1

envoy:
  image: docker.io/envoyproxy/envoy
  tag: v1.17.1
  serviceType:
  metricsScrapeInterval:

nodeAffinity: {}
# nodeAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#     - matchExpressions:
#       - key: network.lokomotive.io
#         operator: Exists


tolerations: []
# tolerations:
# - effect: NoSchedule
#   key: network.lokomotive.io
#   operator: Equal
#   value: contour
