apiVersion: v1
kind: Secret
metadata:
  name: azure-application-password
type: Opaque
data:
  azure-application-password: {{ .Values.applicationPassword | required "password required" | b64enc | quote }}
