apiserver:
  apiserverKey: ${apiserver_key}
  apiserverCert: ${apiserver_cert}
  serviceAccountPub: ${serviceaccount_pub}
  caCert: ${ca_cert}
  etcdClientCaCert: ${etcd_ca_cert}
  etcdClientCert: ${etcd_client_cert}
  etcdClientKey: ${etcd_client_key}
  aggregationCaCert: ${aggregation_ca_cert}
  aggregationClientCert: ${aggregation_client_cert}
  aggregationClientKey: ${aggregation_client_key}
  image: ${kube_apiserver_image}
  cloudProvider: ${cloud_provider}
  etcdServers: ${etcd_servers}
  enableAggregation: ${enable_aggregation}
  serviceCIDR: ${service_cidr}
  trustedCertsDir: ${trusted_certs_dir}
  replicas: ${replicas}
  enableTLSBootstrap: ${enable_tls_bootstrap}
  %{~ if length(extra_flags) > 0 ~}
  extraFlags:
  %{~ for f in extra_flags ~}
  - ${f}
  %{~ endfor ~}
  %{~ endif ~}
